[[main]]
    # Top-level menu entry
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 1

[[main]]
    # Top-level menu entry
    identifier = "writing"
    name = "Writing"
    url = "/posts/"
    weight = 2

